### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AdySan** [joannalawniczak/karak-studio#3]
hello there,

Your static layouts are beautiful! Although I don't understand much of node, js, etc. I've been able to build and customize these sites. I plan to use it for a simple website as an ad for selling my house. However, I don't see any form of licensing info here. Before I go ahead and fork this repo, just wanted to get an OK from you. Any objection?

Regards,
Ady

**Comment by joannalawniczak** [comment]
Hello Ady,

I'm glad you like it, that is kind. But this project is unlicenced on purpose. It cannot be reused. I publish it as my portfolio.

Best!
Joanna
